---
title: "facebook clustering"
author: "CCP"
date: "1/8/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Libraries
```{r}
library(tidyverse)
library(data.table)
library(magrittr)
```

# Data
```{r}
setwd("~/Documents/dartmouth/research/aim3_facebook_covid19_obesity/data")
obesity <- fread("211105_feature_matrix_bert.csv")
lda_topics <- fread("220108_lda_topic_probabilities.csv")
#kmeans <- fread("220108_kmeans_centroids.csv")
#dbscan <- fread("221106_dbscan_labels.csv")
```

# Assigning Final Label to Eventually Combine Data
```{r}
obesity$corpus_index = seq(1, nrow(obesity))
lda_topics$corpus_index = seq(1, nrow(lda_topics))
#kmeans$corpus_index = seq(1, nrow(kmeans))
#dbscan$corpus_index = seq(1, nrow(dbscan))
```

# Picking Label for LDA Based on Max Prob.
```{r}
set.seed(110295)
lda_topics %<>%
  replace(is.na(.), 0)

lda_topics %<>%
  mutate(lda_topic = colnames(lda_topics)[3:6][max.col(lda_topics[,3:6],
                                                       ties.method="random")])
```

# Combine Feature Matrix and Topic
```{r}
obesity %<>%
  select(-V1, -index) %>%
  left_join(lda_topics, by = "corpus_index")
#180,481 in "0",
#268,856 in "1",
#103,479 in "2",
#77,144 in "3"
```

# Psycholinguistic Differences Between Clusters
```{r}
head(obesity)
obesity_liwc <- obesity %>% 
  select(WC:OtherP, lda_topic)

liwc_p_values <- c()
for (liwc in colnames(obesity_liwc)[1:length(colnames(obesity_liwc))-1]) {
  liwc_p_values <- c(liwc_p_values, 
                     summary(aov(get(liwc) ~ lda_topic, 
                                 data = obesity_liwc))[[1]][["Pr(>F)"]][1])
}
fdr_p_values <- p.adjust(liwc_p_values, method = "fdr")
which(fdr_p_values > 0.05)

for (liwc in colnames(obesity_liwc)[1:length(colnames(obesity_liwc))-1]) {
  print(liwc)
  print(TukeyHSD(aov(get(liwc) ~ lda_topic,
             data = obesity_liwc)))
  print("**********")
}
``` 

