---
title: "facebook clustering"
author: "CCP"
date: "1/8/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Libraries
```{r}
library(tidyverse)
library(data.table)
library(magrittr)
library(janitor)
library(scales)
library(zoo)
library(tseries)
library(forecast)
library(tidytext)
library(RColorBrewer)
```

# Data
```{r}
setwd("~/Documents/dartmouth/research/aim3_facebook_covid19_obesity/data")
obesity_topics <- fread("220325_obesity_with_topics.csv") %>%
  clean_names()
```

# Function
## ADF Test
```{r}
arima_its_adf_test <- function(its_date, 
                      dat, 
                      post_or_interaction = "post",
                      summary = FALSE) {
  first_date = as.Date(its_date) - 14
  last_date = as.Date(its_date) + 14
  
  dat_filtered <- dat %>%
      dplyr::filter(post_created_date >= first_date &
                    post_created_date <= last_date)
  
  date_seq <- seq.Date(from = as.Date(first_date),
                         length.out = nrow(dat_filtered),
                         by = 1)

  if (post_or_interaction == "post") {
      dat_ts <- ts(as.numeric(dat_filtered$posts_per_day), 
                              start = first_date,
                              frequency = 365)

  } else {
      dat_ts <- ts(as.numeric(dat_filtered$interactions_per_day), 
                                   start = first_date,
                                   frequency = 365)
  }
  
  if (summary == FALSE) {
    print(adf.test(dat_ts)) #Stationary data if significant (we want stationary)
  } else {
    adf_summary <- adf.test(dat_ts)
    if (adf_summary$p.value > 0.05) {
      print(paste0("Difference (p = ", round(adf_summary$p.value, 3), ")"))
    } else {
      print(paste0("No Difference Needed (p = ", round(adf_summary$p.value, 3), ")"))
    }
  }
}
```

## ARIMA- ITS
```{r}
## Note: If adf.test is not significant, that means data needs to be differenced and this function re-run with difference = TRUE. This function does not difference the data. 
arima_its <- function(its_date, 
                      dat, 
                      difference = NA,
                      pulse = FALSE,
                      step = FALSE,
                      ramp = FALSE,
                      post_or_interaction = "post",
                      aic_only = FALSE) {

  first_date = as.Date(its_date) - 14
  last_date = as.Date(its_date) + 14
  
  dat_filtered <- dat %>%
      dplyr::filter(post_created_date >= first_date &
                    post_created_date <= last_date)
  
  date_seq <- seq.Date(from = as.Date(first_date),
                         length.out = nrow(dat_filtered),
                         by = 1)

  if (post_or_interaction == "post") {
      dat_ts <- ts(as.numeric(dat_filtered$posts_per_day), 
                              start = first_date,
                              frequency = 365)

  } else {
      dat_ts <- ts(as.numeric(dat_filtered$interactions_per_day), 
                                   start = first_date,
                                   frequency = 365)
  }
  
  #print(adf.test(dat_ts)) #Stationary data if significant (we want stationary)

## Step Parameter
  transfer <- c()
  if (step == TRUE) {
    dat_step <- ifelse(date_seq >= its_date, 1, 0)
    transfer <- cbind(transfer, dat_step)
  }

## Ramp Parameter
  if (ramp == TRUE) {
    dat_step <- ifelse(date_seq >= its_date, 1, 0)
    dat_ramp <- append(rep(0,
                         length(which(dat_step == 0))),
                     seq(1,
                         length(which(dat_step == 1)),
                         1))
    transfer <- cbind(transfer, dat_ramp)
  }
## Pulse Parameter
  if (pulse == TRUE) {
    dat_pulse <- ifelse(date_seq == its_date, 1, 0)
    transfer <- cbind(transfer, dat_pulse)
  }

  if (!is.na(difference)) {
    #print(paste0("Running with differencing of ", difference))
      model_func <- auto.arima(dat_ts,
                               d = difference, #Considers differencing data
                               xreg = transfer)
  } else {
    #print("Running with no differencing")
      model_func <- auto.arima(dat_ts,
                               xreg = transfer)
  }

  #print(Box.test(model_func$residuals, 
  #         type = "Ljung-Box")) 

  if (aic_only == TRUE) {
    return(model_func$aicc)
  }
  else {
    print(summary(model_func))
    print(confint(model_func))
    print((1-pnorm(abs(model_func$coef)/sqrt(diag(model_func$var.coef))))*2) 
  }
}
```

# Number of Posts per Topic
```{r}
nrow(obesity_topics)
View(obesity_topics %>%
  group_by(topics) %>%
  count())

obesity_topics %<>%
  filter(topics >= 0 & topics <= 12 & !(topics %in% c(5, 6, 9))) #34,868 posts

obesity_topics %<>%
  mutate(topic_renamed = paste0("Topic: ", topics))

obesity_topics %>%
  group_by(topic_renamed) %>%
  summarise(count = n()) %>%
  ggplot(aes(y = reorder(topic_renamed, count),
             x = count)) +
  geom_bar(stat = "identity",
           color = "black",
           fill = "#4267B2") +
  theme_classic() +
  labs(x = "Count",
       y = "Topic Number",
       title = "Number of Posts per BERTopic - Facebook")
#setwd("~/Documents/dartmouth/research/aim3_facebook_covid19_obesity/figures")
#ggsave("220303_topic_counts.tiff",
#       width = 7.25,
#       height = 4.51)
```

# Distribution of Interactions per Topic
```{r}
obesity_topics %<>%
    mutate(total_interactions_numeric =
             as.numeric(str_remove_all(total_interactions, 
                                       " ")))

View(obesity_topics %>%
       group_by(topic_renamed) %>%
       summarise(median(total_interactions_numeric,
                     na.rm = TRUE),
              quantile(total_interactions_numeric,
                       0.25,
                       na.rm = TRUE),
              quantile(total_interactions_numeric,
                       0.75,
                       na.rm = TRUE)))
     
obesity_topics %>%
  group_by(topic_renamed) %>%
  filter(total_interactions_numeric > 0) %>%
  mutate(median_total_interaction = median(log10(total_interactions_numeric),
                                         na.rm = TRUE)) %>%
  ggplot(aes(x = log10(total_interactions_numeric),
             y = reorder(topic_renamed, 
                         median_total_interaction))) +
  geom_boxplot(color = "black",
               fill = "#4267B2") +
  theme_classic() +
  labs(x = "Log (Base 10) Interactions",
       y = "Topic Number",
       title = "Distribution of Interactions per BERTopic - Facebook")
#setwd("~/Documents/dartmouth/research/aim3_facebook_covid19_obesity/figures")
#ggsave("220303_interaction_distribution_facebook.tiff",
#       width = 7.25,
#       height = 4.51)
```

## By Interaction Type
```{r}
obesity_topics %>%
  #mutate(lda_facet = gsub("Topic: ", "", lda_topic_renamed)) %>%
  group_by(topic_renamed) %>%
  select(likes, comments, shares, love, wow, haha, sad, angry, care, topic_renamed) %>%
  melt(id = "topic_renamed") %>%
  mutate(value = as.numeric(gsub(" ", "", value)),
         log_value = log10(value)) %>%
  filter(value > 0) %>%
  ggplot(aes(x = reorder_within(topic_renamed,
                                log_value,
                                variable,
                                median),
             y = log_value,
             fill = variable)) +
  geom_boxplot(color = "black",
               outlier.size = 0.05,
               position = position_dodge(width = 2)) +
  theme_classic() +
  facet_wrap(~variable,
             scales = "free_y") +
  scale_x_reordered() +
  scale_fill_manual(values = c("#A0CBE8",
                                "#F28E2B",
                                "#8CD17D",
                                "#F1CE63",
                                "#86BCB6",
                                "#FF9D9A",
                                "#BAB0AC",
                                "#FABFD2",
                                "#D4A6C8")) + 
  coord_flip() + 
  theme(axis.text.y = element_text(size = 6),
        legend.position = "none") +
  labs(y = "Log (Base 10) Count",
       x = "Topic",
       title = "Distribution of Interactions by Type and Topic - Facebook")
#setwd("~/Documents/dartmouth/research/aim3_facebook_covid19_obesity/figures")
#ggsave("220304_interaction_distribution_facebook_facet.tiff",
#       width = 7.25,
#       height = 4.51)

View(obesity_topics %>%
  group_by(topic_renamed) %>%
  select(likes, comments, shares, love, wow, haha, sad, angry, care, topic_renamed) %>%
  melt(id = "topic_renamed") %>%
  mutate(value = as.numeric(gsub(" ", "", value)),
         log_value = log10(value)) %>%
  group_by(topic_renamed, variable) %>%
  summarise(median(value, na.rm = TRUE),
            quantile(value, 0.25, na.rm = TRUE),
            quantile(value, 0.75, na.rm = TRUE)))
```

# Plot of Count per Day
```{r}
obesity_topics %>%
  mutate(date_date = as.Date(post_created_date)) %>%
  group_by(topic_renamed, date_date) %>%
  summarise(count_per_day = n()) %>%
  mutate(topic_renamed = factor(topic_renamed,
                                    levels = c("Topic: 0", "Topic: 1", "Topic: 2", "Topic: 3", "Topic: 4", "Topic: 7", "Topic: 8", "Topic: 10", "Topic: 11", "Topic: 12")),
         topics_facet = case_when(
           topic_renamed == "Topic: 0" ~ "COVID-19",
           topic_renamed == "Topic: 1" ~ "Childhood Obesity",
           topic_renamed == "Topic: 2" ~ "Sugary Drinks",
           topic_renamed == "Topic: 3" ~ "Bariatric Surgery",
           topic_renamed == "Topic: 4" ~ "Weight Loss Stories",
           topic_renamed == "Topic: 7" ~ "Clickbait",
           topic_renamed == "Topic: 8"~ "Cancer",
           topic_renamed == "Topic: 10" ~ "Sleep",
           topic_renamed == "Topic: 11" ~ "Yoga",
           topic_renamed == "Topic: 12" ~ "Heart Disease"
         )) %>%
  filter(date_date >= as.Date("2020-01-06"),
         date_date <= as.Date("2020-10-016")) %>%
  ggplot(aes(x = date_date,
             y = count_per_day,
             color = topics_facet)) +
  geom_vline(xintercept = c(as.Date("2020-01-20"),
                            as.Date("2020-03-11"),
                            as.Date("2020-05-19"),
                            as.Date("2020-10-02")),
             linetype = "dashed",
             color = "black") + 
  geom_line(size = 0.5) +
  facet_wrap(~topics_facet,
             scales = "free_y") + 
  scale_color_manual(values = c("#9E0142",
                                "#D53E4F",
                                "#F46D43",
                                "#FDAE61",
                                "#FEE08B",
                                "#ABDDA4", 
                                "#66C2A5",
                                "#3288BD",
                                "#5E4FA2",
                                "darkgray")) +
  theme_classic() +
  theme(legend.position = "none") + 
  labs(x = "Date",
       y = "Count",
       title = "Number of Posts per Topic Per Day - Facebook")
#setwd("~/Documents/dartmouth/research/aim3_facebook_covid19_obesity/figures")
#ggsave("220412_topics_per_day_facet.tiff",
#       width = 7.25, 
#       height = 4.51)
```

# Metadata Analysis
```{r}
obesity_date_restricted <- obesity_topics %>%
    filter(!is.na(post_created_date),
           post_created_date >= as.Date("2020-01-06"),
           post_created_date <= as.Date("2020-10-16"))

View(obesity_topics %>%
  filter(page_category != "none") %>%
  group_by(topics) %>%
  mutate(denominator = n()) %>%
  group_by(topics, page_category) %>%
  summarise(count = n(),
            percent = round(count/denominator*100, 2)) %>%
  arrange(topics, desc(count)) %>%
  distinct(.) %>%
  ungroup() %>%
  group_by(topics) %>%
  filter(row_number() <= 1))

View(obesity_topics %>%
       group_by(page_category, page_name) %>%
       summarise(count = n()) %>%
       arrange(desc(count)) %>%
       ungroup() %>%
       group_by(page_category) %>%
       filter(row_number() == 1))

View(obesity_topics %>%
  group_by(topic_renamed) %>%
  select(likes_at_posting, followers_at_posting, topic_renamed) %>%
  melt(id = "topic_renamed") %>%
  mutate(value = as.numeric(gsub(" ", "", value)),
         log_value = log10(value)) %>%
  group_by(topic_renamed, variable) %>%
  summarise(median(value, na.rm = TRUE),
            quantile(value, 0.25, na.rm = TRUE),
            quantile(value, 0.75, na.rm = TRUE)))

```

# Evaluating Number of LDA Clusters Over Time
## Running ARIMA
### Setting up Data
```{r}
list_of_its_dates <- c(as.Date("2020-01-20"),
                       as.Date("2020-03-11"),
                       as.Date("2020-05-19"),
                       as.Date("2020-10-02"))

topics_per_day <- obesity_date_restricted %>%
  group_by(topics, post_created_date) %>%
  summarise(posts_per_day = n()) %>%
  filter(!is.na(post_created_date))

for (i in min(topics_per_day$topics):max(topics_per_day$topics)) {
  if (i %in% c(5, 6, 9)) {
    next
  }
  assign(paste0("topics_per_day_", i), topics_per_day %>%
           filter(topics == i))
}

dfs <- c("topics_per_day_0", "topics_per_day_1", "topics_per_day_2", "topics_per_day_3", "topics_per_day_4", "topics_per_day_7", "topics_per_day_8", "topics_per_day_10", "topics_per_day_11", "topics_per_day_12")
```

### Checking Which Transfer Functions to Use
```{r}
aic_table <- NULL
for (df in dfs) {
  for (d in list_of_its_dates) {
    if (d == 18281 & df == "topics_per_day_0") {
      next
    }
    print(as.Date(d))
    print(df)
    aic_pulse = arima_its(d, get(df), pulse = TRUE, aic_only = TRUE)

    aic_step = arima_its(d, get(df), step = TRUE, aic_only = TRUE)

    aic_ramp = arima_its(d, get(df), ramp = TRUE, aic_only = TRUE)

    aic_pulse_step = arima_its(d, get(df), 
              pulse = TRUE, 
              step = TRUE, aic_only = TRUE)

    aic_pulse_ramp =  arima_its(d, get(df), 
                                pulse = TRUE, ramp = TRUE, aic_only = TRUE)

    aic_step_ramp = arima_its(d, get(df), 
                              step = TRUE, ramp = TRUE, aic_only = TRUE)

    aic_all = arima_its(d, get(df),
              pulse = TRUE, step = TRUE, ramp = TRUE, aic_only = TRUE)
    aic_table <- rbind(aic_table, 
                       cbind(df, d, 
                             aic_pulse, aic_step, aic_ramp, aic_pulse_step, aic_pulse_ramp, 
                             aic_step_ramp, aic_all))
  }
}

aic_table %<>%
  as.data.frame()

aic_table$best_transfer_function <- apply(aic_table, 1, FUN = function(x) names(x)[which.min(x)])

aic_table %<>%
  mutate_at(c("aic_pulse", "aic_step", "aic_ramp", "aic_pulse_step", "aic_pulse_ramp", "aic_step_ramp", "aic_all"),
            as.numeric) %>%
  rowwise() %>%
  mutate(best_aic = round(min(aic_pulse, aic_step, aic_ramp, aic_pulse_step, aic_pulse_ramp, aic_step_ramp, aic_all), 3)) %>%
  as.data.frame()

View(aic_table %>% select(df, d, best_aic, best_transfer_function))
```

### Running Models - Individual
```{r}
# January 20th
for (df in dfs) {
  print(df)
  p = FALSE
  r = FALSE
  s = FALSE
  if (df %in% c("topics_per_day_3", "topics_per_day_7", "topics_per_day_12")) {
    p = TRUE
  }
  if (df %in% c("topics_per_day_8", "topics_per_day_10", "topics_per_day_11")) {
    s = TRUE
  }
  if (df %in% c("topics_per_day_1", "topics_per_day_2", "topics_per_day_4", "topics_per_day_11")) {
    r = TRUE
  }
  if (df == "topics_per_day_0") {
    next
  }
  arima_its(as.Date("2020-01-20"),
            get(df),
            pulse = p,
            step = s,
            ramp = r)
}

# March 11th
for (df in dfs) {
  print(df)
  p = FALSE
  r = FALSE
  s = FALSE
  if (df %in% c("topics_per_day_3", "topics_per_day_12")) {
    p = TRUE
  }
  if (df %in% c("topics_per_day_1", "topics_per_day_7", "topics_per_day_10")) {
    s = TRUE
  }
  if (df %in% c("topics_per_day_0", "topics_per_day_2", "topics_per_day_4", "topics_per_day_8", "topics_per_day_10", "topics_per_day_11")) {
    r = TRUE
  }
  arima_its(as.Date("2020-03-11"),
            get(df),
            pulse = p,
            step = s,
            ramp = r)
}

# May 19th
for (df in dfs) {
  print(df)
  p = FALSE
  r = FALSE
  s = FALSE
  if (df %in% c("topics_per_day_0", "topics_per_day_3", "topics_per_day_7", "topics_per_day_8", "topics_per_day_11", "topics_per_day_12")) {
    p = TRUE
  }
  if (df %in% c("topics_per_day_1", "topics_per_day_2", "topics_per_day_4", "topics_per_day_7", "topics_per_day_10")) {
    s = TRUE
  }
  if (df %in% c("topics_per_day_7")) {
    r = TRUE
  }
  arima_its(as.Date("2020-05-19"),
            get(df),
            pulse = p,
            step = s,
            ramp = r)
}

# October 2nd
for (df in dfs) {
  print(df)
  p = FALSE
  r = FALSE
  s = FALSE
  if (df %in% c("topics_per_day_0", "topics_per_day_10", "topics_per_day_11")) {
    p = TRUE
  }
  if (df %in% c("topics_per_day_1", "topics_per_day_7", "topics_per_day_12")) {
    s = TRUE
  }
  if (df %in% c("topics_per_day_2", "topics_per_day_3", "topics_per_day_4", "topics_per_day_8")) {
    r = TRUE
  }
  arima_its(as.Date("2020-10-02"),
            get(df),
            pulse = p,
            step = s,
            ramp = r)
}

```

# Topic Distribution Around Key Dates
```{r}
topic_distribution_jan <- obesity_topics %>%
  filter(post_created_date <= as.Date("2020-01-20") + 14) %>%
  group_by(topic_renamed) %>%
  count() %>%
  mutate(date = "Jan. 6 - Feb. 3, 2020")

topic_distribution_mar <- obesity_topics %>%
  filter(post_created_date <= as.Date("2020-03-11") + 14 &
           post_created_date >= as.Date("2020-03-11") - 14) %>%
  group_by(topic_renamed) %>%
  count() %>%
  mutate(date = "Feb. 26 - Mar. 25, 2020")

topic_distribution_may <- obesity_topics %>%
  filter(post_created_date <= as.Date("2020-05-19") + 14 &
           post_created_date >= as.Date("2020-05-19") - 14) %>%
  group_by(topic_renamed) %>%
  count() %>%
  mutate(date = "May 5 - June 2, 2020")

topic_distribution_oct <- obesity_topics %>%
  filter(post_created_date <= as.Date("2020-10-02") + 14 &
           post_created_date >= as.Date("2020-10-02") - 14) %>%
  group_by(topic_renamed) %>%
  count() %>%
  mutate(date = "Sept. 18 - Oct. 16, 2020")

topic_distribution <- rbind(topic_distribution_jan, topic_distribution_mar, topic_distribution_may, topic_distribution_oct)

topic_distribution %>%
  arrange(desc(n)) %>%
  mutate(topic_renamed = factor(topic_renamed,
                                    levels = c("Topic: 0", "Topic: 1", "Topic: 2", "Topic: 3", "Topic: 4", "Topic: 7", "Topic: 8", "Topic: 10", "Topic: 11", "Topic: 12")),
         topics_facet = case_when(
           topic_renamed == "Topic: 0" ~ "COVID-19",
           topic_renamed == "Topic: 1" ~ "Childhood Obesity",
           topic_renamed == "Topic: 2" ~ "Sugary Drinks",
           topic_renamed == "Topic: 3" ~ "Bariatric Surgery",
           topic_renamed == "Topic: 4" ~ "Weight Loss Stories",
           topic_renamed == "Topic: 7" ~ "Clickbait",
           topic_renamed == "Topic: 8"~ "Cancer",
           topic_renamed == "Topic: 10" ~ "Sleep",
           topic_renamed == "Topic: 11" ~ "Yoga",
           topic_renamed == "Topic: 12" ~ "Heart Disease"
         ),
         date = relevel(as.factor(date), ref = "Jan. 6 - Feb. 3, 2020")) %>%
  ggplot(aes(x = n,
             y = reorder_within(topics_facet,
                                n,
                                date), 
             fill = topics_facet)) +
  geom_bar(stat = "identity", color = "black") +
  facet_wrap(~date, scales = "free_y") +
  theme_classic() + 
  scale_y_reordered() +
  scale_fill_manual(values = c("#9E0142",
                                "#D53E4F",
                                "#F46D43",
                                "#FDAE61",
                                "#FEE08B",
                                "#ABDDA4", 
                                "#66C2A5",
                                "#3288BD",
                                "#5E4FA2",
                                "grey")) +
  theme(legend.position = "none") +
  labs(x = "Count",
       y = "Topic",
       title = "Distribution of Posts Around Each Date of Interest")
setwd("~/Documents/dartmouth/research/aim3_facebook_covid19_obesity/figures")
ggsave("220425_topics_per_time_period_aggregate_facebook.tiff",
       width = 7.25, 
       height = 4.51)
```

